language: python

python:
    - 3.6

install:
    - pip install -r requirements.txt

script:
    - isort -rc -cs -s migrations --diff --check-only recommender
    - flake8 --exclude=migrations --max-line-length 119 recommender
